version: '3.8'

services:

  api:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: token-auth-server
    
    volumes:
      - '${PWD}/api:/api'
    depends_on:
      - api_mongo
    ports:
      - "3001:3001"
    networks:
      - backend
      - database
    env_file:
      - '.env'      

  api_mongo:
    image: mongo:latest
    container_name: api_mongo
    volumes:
      - mongodb_api:/data/db
    ports:
      - '27017:27017'
    networks:
      - database
    env_file:
      - '.env'      

volumes:
  mongodb_api:

networks:
  frontend:
  backend:  
  database: