FROM node:16-alpine3.12 as build-stage

RUN mkdir /app
WORKDIR /app

COPY package*.json ./
RUN yarn install 

COPY ./ .

RUN yarn build

FROM nginx:stable-alpine as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY /nginx/nginx.conf /etc/nginx/nginx.conf

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

EXPOSE 3002
#CMD ["nginx", "-g", "daemon off;"]