name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]    

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest] # [macos-latest, ubuntu-latest, windows-latest]
        deno_version: [1.17.1, 1.17.2]
    runs-on: ${{ matrix.os }}
    env:
      working_directory: ./api
    steps:
      - uses: actions/checkout@v2.4.0
      - name: Use Deno Version ${{ matrix.deno_version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno_version }}
      # - name: Lint Deno Module
      #   run: deno fmt --check
      - name: Cache files
        run: |
          cd api
          DENO_ENV=CI deno run -A --import-map=import_map.json --unstable Drakefile.ts cache
        working-directory: ${{env.working-directory}}
        env:
          DENO_ENV: CI
      - name: Run tests          
      - run: |
          cd api
          DENO_ENV=CI deno run -A --import-map=import_map.json --unstable Drakefile.ts test
        working-directory: ${{env.working-directory}}
        env:
          DENO_ENV: test
      - name: Build / Bundle Project
        # This happens when the pull request has been approved
        if: github.event_name == 'push'  
        run: |
          cd api
          DENO_ENV=CI deno run -A --import-map=import_map.json --unstable Drakefile.ts bundle
